<Project><PropertyGroup><TargetFramework>net8.0-windows</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><LangVersion>12</LangVersion><PlatformTarget>x64</PlatformTarget><Deterministic>true</Deterministic><Version>1.7.0</Version><Company>CleanC</Company><Copyright>Copyright © 2026 CleanC</Copyright></PropertyGroup></Project>
