<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType></PropertyGroup><ItemGroup><ProjectReference Include="../../src/CleanC.Licensing/CleanC.Licensing.csproj"/><ProjectReference Include="../../src/CleanC.Scanner/CleanC.Scanner.csproj"/><ProjectReference Include="../../src/CleanC.Cleaner/CleanC.Cleaner.csproj"/><ProjectReference Include="../../src/CleanC.Repair/CleanC.Repair.csproj"/></ItemGroup></Project>
