<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../CleanC.Core/CleanC.Core.csproj"/><ProjectReference Include="../CleanC.Logging/CleanC.Logging.csproj"/><PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0"/><EmbeddedResource Include="Crypto/cleanc-public.pem"/><EmbeddedResource Include="Crypto/offline-public.pem"/></ItemGroup></Project>
